apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app2-deployment
  annotations:
    app-description: "This is ubuntu/apache image"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app2
  template:
    metadata:
      labels:
        app: my-app2
    spec:
      containers:
      - name: my-app-container
        image: mydocker1405/sample-k8s-image:v1
        ports:
        - containerPort: 8080
